
; VERSÃO BAIXO NÍVEL    

#INCLUDE <P16F628A.INC>

 __CONFIG _FOSC_EXTRCCLK & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _BOREN_ON & _LVP_ON & _CPD_OFF & _CP_OFF

VALOR EQU 0X20

 ORG 0
 GOTO INIT
 
 ORG 4
    
    BANKSEL RCREG
    MOVF RCREG,W
    MOVWF VALOR
       
    BANKSEL VALOR
    BTFSS VALOR, 0
    RETFIE
    BTFSS VALOR, 1
    RETFIE
    BTFSC VALOR, 2
    RETFIE
    BTFSS VALOR, 3 ; CERTAMENTE É A LETRA K (LETRA, N IMPORTA SE TEM SIMBOLOS PARECIDOS COM)
    RETFIE
    GOTO ENVIAR_NOME

    ENVIAR_NOME: 
    
    MOVLW B'00100000' ; ESPAÇO
    CALL ESPERAR_TX
    MOVWF TXREG
    
    MOVLW 0X59
    CALL ESPERAR_TX
    MOVWF TXREG

    MOVLW 0X41
    CALL ESPERAR_TX
    MOVWF TXREG
    
    MOVLW 0X4E
    CALL ESPERAR_TX
    MOVWF TXREG

    RETFIE
    
    ESPERAR_TX: 
    
    BANKSEL PIR1
    BTFSS PIR1, TXIF    ; Espera até TXIF estar setado
    GOTO ESPERAR_TX
    RETURN
    
INIT
    BANKSEL TRISB
    MOVLW B'00000110'
    MOVWF TRISB
    MOVLW B'00100110'
    MOVWF TXSTA
    MOVLW D'25'
    MOVWF SPBRG
    CLRF PIE1
    BSF PIE1,RCIE
    
    BANKSEL RCSTA
    MOVLW B'10010000'
    MOVWF RCSTA
    CLRF PIR1
    MOVLW B'11000000'
    MOVWF INTCON
    
    FIM
	GOTO FIM
	
END
    


; A flag RCIF só será limpa automaticamente ao ler o registrador RCREG, logo não é necessário ter que limpar ela na rotina de interrupção